language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
install: 
  - if [ "$TRAVIS_PYTHON_VERSION" == "3.2" ]; then travis_retry pip install coverage==3.7.1; fi
  - if [ "$TRAVIS_PYTHON_VERSION" != "3.2" ]; then travis_retry pip install coverage; fi
  - "pip install pep8"
script: pep8 country.py